import React, { useState, FC, ChangeEvent } from 'react'
import Head from 'next/head'
import { ITask } from './interfaces'

const Home: FC = () => {
  
  const [isTask, setTask] = useState<string>('')
  const [isTime, setTime] = useState<number>(0)
  const [isObject, setObject] = useState<ITask[]>([])
  
  const addTask = (): void => {
    const newTask = { nameTask: isTask, deadline: isTime}
    setObject([...isObject, newTask])
    setTask('')
    setTime(0)
  }

  const handleChange = (event: ChangeEvent<HTMLInputElement>): void => {
    if(event.target.name === "task"){
      setTask(event.target.value)
    }else{
      setTime(Number(event.target.value))
    }
  }

  return(
    <>
      <Head>
        <title>TodoApp React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className='main'>
        <input type="text" placeholder='Text...' onChange={handleChange}/>
        <input type="text" placeholder='Time...' onChange={handleChange}/>
        <button onClick={addTask}>Send</button>
      </div>
    </>
  )
}

export default Home