import React, { FC, ChangeEvent, useState } from 'react'
import Head from 'next/head'
import {ITask} from './interfaces'
import TodoTask from '../components/task/task'
import Footer from '../components/footer/footer'

const Home: FC = () => {
  
  const [task, setTask] = useState<string>("")
  const [deadline, setDeadline] = useState<number>(0)
  const [todoList, setTodoList] = useState<ITask[]>([])

  const handleChange = (event: ChangeEvent<HTMLInputElement>): void => {
    if(event.target.name === 'task'){
      setTask(event.target.value)
    }else{
      setDeadline(Number(event.target.value))
    }
  } 

  const addTask = (): void => {
    const newTask = { nameTask: task, deadline: deadline }
    setTodoList([...todoList, newTask])
    setTask("")
    setDeadline(0)
  }

  return (
    <>
      <Head>
        <title>TodoApp React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className='main'>
        <input 
          type="text" 
          placeholder='Task...' 
          name="task"
          value={task}
          onChange={handleChange} 
        />
        <input 
          type="number" 
          placeholder='Deadline(in days)...'
          name="deadline" 
          value={deadline}
          onChange={handleChange} 
        />
        <button onClick={addTask}>Send</button>
      </div>
      <div>
        {todoList.map((task: ITask, key: number) => {
          return <TodoTask key={key} task={task} />
        })}
      </div>
      <Footer />
    </>
  )
}

export default Home
